# Site settings
title: Ally's Coding Journey - Blog
header-img: img/home-bg.png
email: netzelally@gmail.com
copyright_name: netzay
description: > # this means to ignore newlines until "baseurl:"
  Ally's Blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  netzay
learn_profile: netzay
email_username: netzelally@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
